<?php

// Only CRUD-capable resources are listed here. 'full' = view+create+update+delete,
// 'view' = read-only, absent/'none' = no access at all (page hidden, API blocked).
return [

    'products' => [
        'Admin' => 'full',
        'Manager' => 'full',
        'Accountant' => 'view',
        'Auditor' => 'view',
        'Warehouse Supervisor' => 'full',
        'Cashier' => 'view',
        'SaleS Staff' => 'full',
        'HR Officer' => 'none',
        'IT Support' => 'none',
        'Delivery Driver' => 'none',
        'Viewer' => 'none',
    ],

    'categories' => [
        'Admin' => 'full',
        'Manager' => 'full',
        'Accountant' => 'none',
        'Auditor' => 'view',
        'Warehouse Supervisor' => 'full',
        'Cashier' => 'none',
        'SaleS Staff' => 'full',
        'HR Officer' => 'none',
        'IT Support' => 'none',
        'Delivery Driver' => 'none',
        'Viewer' => 'none',
    ],

    'suppliers' => [
        'Admin' => 'full',
        'Manager' => 'full',
        'Accountant' => 'view',
        'Auditor' => 'view',
        'Warehouse Supervisor' => 'full',
        'Cashier' => 'none',
        'SaleS Staff' => 'full',
        'HR Officer' => 'none',
        'IT Support' => 'none',
        'Delivery Driver' => 'none',
        'Viewer' => 'none',
    ],

    'purchases' => [
        'Admin' => 'full',
        'Manager' => 'full',
        'Accountant' => 'full',
        'Auditor' => 'view',
        'Warehouse Supervisor' => 'full',
        'Cashier' => 'none',
        'SaleS Staff' => 'full',
        'HR Officer' => 'none',
        'IT Support' => 'none',
        'Delivery Driver' => 'none',
        'Viewer' => 'none',
    ],

    'sales' => [
        'Admin' => 'full',
        'Manager' => 'full',
        'Accountant' => 'full',
        'Auditor' => 'view',
        'Warehouse Supervisor' => 'none',
        'Cashier' => 'full',
        'SaleS Staff' => 'full',
        'HR Officer' => 'none',
        'IT Support' => 'none',
        'Delivery Driver' => 'view',
        'Viewer' => 'none', // driver: own deliveries only, see note below
    ],

    'customers' => [
        'Admin' => 'full',
        'Manager' => 'full',
        'Accountant' => 'view',
        'Auditor' => 'view',
        'Warehouse Supervisor' => 'none',
        'Cashier' => 'full',
        'SaleS Staff' => 'full',
        'HR Officer' => 'none',
        'IT Support' => 'none',
        'Delivery Driver' => 'view',
        'Viewer' => 'none',
    ],

    'departments' => [
        'Admin' => 'full',
        'Manager' => 'view',
        'Accountant' => 'none',
        'Auditor' => 'view',
        'Warehouse Supervisor' => 'none',
        'Cashier' => 'none',
     'SaleS Staff' => 'full',
        'HR Officer' => 'full',
        'IT Support' => 'view',
        'Delivery Driver' => 'none',
        'Viewer' => 'none',
    ],

    'roles' => [
        'Admin' => 'full',
        'Manager' => 'none',
        'Accountant' => 'none',
        'Auditor' => 'view',
        'Warehouse Supervisor' => 'none',
        'Cashier' => 'none',
        'Staff' => 'none',
        'HR Officer' => 'view',
        'IT Support' => 'view',
        'Delivery Driver' => 'none',
        'Viewer' => 'none',
    ],

    'users' => [
        'Admin' => 'full',
        'Manager' => 'view',
        'Accountant' => 'none',
        'Auditor' => 'view',
        'Warehouse Supervisor' => 'none',
        'Cashier' => 'none',
        'Staff' => 'none',
        'HR Officer' => 'full',
        'IT Support' => 'full',
        'Delivery Driver' => 'none',
        'Viewer' => 'none',
    ],

    // View-only pages — no write routes exist, so every listed role is
    // effectively 'view' regardless of what the table says. Roles NOT
    // listed have no access to the page at all.
    'dashboard' => [
        'Admin',
        'Manager',
        'Accountant',
        'Auditor',
        'Warehouse Supervisor',
        'Cashier',
        'Staff',
        'HR Officer',
        'IT Support',
        'Delivery Driver',
        'Viewer',
    ],
    'stock-histories' => [
        'Admin',
        'Manager',
        'Auditor',
        'Warehouse Supervisor',
        'Staff',
    ],
    'reports' => [
        'Admin',
        'Manager',
        'Accountant',
        'Auditor',
        'Warehouse Supervisor',
        'Viewer',
    ],
    'recommendations' => [
        'Admin',
        'Manager',
        'Auditor',
        'Warehouse Supervisor',
    ],
    'analytics' => [
        'Admin',
        'Manager',
        'Accountant',
        'Auditor',
        'Viewer',
    ],
    'commissions' => [
        'Admin',
        'Manager',
        'Accountant',
        'Auditor',
    ],
    'audit-logs' => [
        'Admin',
        'Auditor',
        'IT Support',
    ],
];
