<?php

namespace App\Models;

use App\Models\Concerns\Auditable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Support\Facades\Crypt;

class User extends Authenticatable
{
    use HasFactory, HasApiTokens, Auditable, Notifiable;

    protected $table = 'users';

    protected $primaryKey = 'user_id';

    public $timestamps = false;

    protected $fillable = [
        'name',
        'email',
        'password',
        'department_id',
        'role_id',
        'phone',
        'status',
        'image_url',
        'salary',
        'id_card_number',
        'hire_date',
        'address',
        'created_at',
        'updated_at',
    ];




    // Never expose password in JSON responses
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_secret',        // never expose the raw secret
        'two_factor_recovery_codes' // never expose recovery codes by default
    ];

    /**
     *  Store the TOTP secret encrypted at rest - never plaintext in the DB.
     **/
    public function setTwoFactorSecretAttribute($value)
    {
        $this->attributes['two_factor_secret'] = $value === null
            ? null
            : Crypt::encryptString($value);
    }

    public function getTwoFactorSecretAttribute($value)
    {
        return $value === null ? null : Crypt::decryptString($value);
    }

    /**
     * Recovery codes - encrypted, stored as JSON array.
     */
    public function setTwoFactorRecoveryCodesAttribute($value)
    {
        $this->attributes['two_factor_recovery_codes'] = $value === null
            ? null
            : Crypt::encryptString(json_encode($value));
    }
    public function getTwoFactorRecoveryCodesAttribute($value)
    {
        return $value === null ? null : json_decode(Crypt::decryptString($value), true);
    }

    // Never write these into audit_logs, even hashed
    protected $auditExclude = [
        'password',
    ];

    protected function casts(): array
    {
        return [
            'password'  => 'hashed',
            'salary'    => 'decimal:2',
            'hire_date' => 'date',
        ];
    }

    // Relationships
    // User belongs to a department
    public function department()
    {
        return $this->belongsTo(Department::class, 'department_id', 'department_id');
    }

    // User belongs to a role
    public function role()
    {
        return $this->belongsTo(Role::class, 'role_id', 'role_id');
    }

    // User has recorded many purchases
    public function purchases()
    {
        return $this->hasMany(Purchase::class, 'user_id', 'user_id');
    }

    // User has recorded many sales
    public function sales()
    {
        return $this->hasMany(Sale::class, 'user_id', 'user_id');
    }

    // Audit log entries generated by this user's actions
    public function auditLogs()
    {
        return $this->hasMany(AuditLog::class, 'user_id', 'user_id');
    }
}
