<?php

namespace App\Models;

use App\Models\Concerns\Auditable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Sanctum\HasApiTokens;
use 

class User extends Authenticatable
{
    use HasFactory, HasApiTokens, Auditable;

    protected $table = 'users';

    protected $primaryKey = 'user_id';

    public $timestamps = false;

    protected $fillable = [
        'name',
        'email',
        'password',
        'department_id',
        'role_id',
        'phone',
        'status',
        'image_url',
        'salary',
        'id_card_number',
        'hire_date',
        'address',
        'created_at',
        'updated_at',
    ];



    // Relationships
    // Never expose password in JSON responses
    protected $hidden = [
        'password',
    ];

    // Never write these into audit_logs, even hashed
    protected $auditExclude = [
        'password',
    ];

    protected function casts(): array
    {
        return [
            'password'  => 'hashed',
            'salary'    => 'decimal:2',
            'hire_date' => 'date',
        ];
    }

    // User belongs to a department
    public function department()
    {
        return $this->belongsTo(Department::class, 'department_id', 'department_id');
    }

    // User belongs to a role
    public function role()
    {
        return $this->belongsTo(Role::class, 'role_id', 'role_id');
    }

    // User has recorded many purchases
    public function purchases()
    {
        return $this->hasMany(Purchase::class, 'user_id', 'user_id');
    }

    // User has recorded many sales
    public function sales()
    {
        return $this->hasMany(Sale::class, 'user_id', 'user_id');
    }

    // Audit log entries generated by this user's actions
    public function auditLogs()
    {
        return $this->hasMany(AuditLog::class, 'user_id', 'user_id');
    }
}
